import React from "react";
import {
  VscHome,
  VscAccount,
  VscLibrary,
  VscChevronDown,
  VscChevronUp,
} from "react-icons/vsc";
export const links = [
  {
    id: 1,
    text: "Home",
    icon: <VscHome />,
    url: "/",
  },
  {
    id: 2,
    text: "Genre",
    icon: <VscLibrary />,
    url: "/genre",
  },
  {
    id: 3,
    text: "Trending",
    icon: <VscAccount />,
    url: "/trending",
  },
];

export const icons = [
  {
    id: 1,
    image:
      "https://res.cloudinary.com/ugwutotheeshoes/image/upload/v1648827303/Trailer/Action/MV5BOGE2NWUwMDItMjA4Yi00N2Y3LWJjMzEtMDJjZTMzZTdlZGE5XkEyXkFqcGdeQXVyODk4OTc3MTY_._V1__uzkz5r.jpg",
    name: "advontura",
    genre: "family, adventure",
    ratings: "/10",
    url: "/1",
    text: "view details",
  },
  {
    id: 2,
    image:
      "https://res.cloudinary.com/ugwutotheeshoes/image/upload/v1648827303/Trailer/Action/MV5BOGE2NWUwMDItMjA4Yi00N2Y3LWJjMzEtMDJjZTMzZTdlZGE5XkEyXkFqcGdeQXVyODk4OTc3MTY_._V1__uzkz5r.jpg",
    name: "scream boi",
    genre: "horror",
    ratings: "/10",
    url: "/1",
    text: "view details",
  },
  {
    id: 3,
    image:
      "https://res.cloudinary.com/ugwutotheeshoes/image/upload/v1648827303/Trailer/Action/MV5BOGE2NWUwMDItMjA4Yi00N2Y3LWJjMzEtMDJjZTMzZTdlZGE5XkEyXkFqcGdeQXVyODk4OTc3MTY_._V1__uzkz5r.jpg",
    name: "home alone with guns",
    genre: "action, comedy",
    ratings: "/10",
    url: "/1",
    text: "view details",
  },
  {
    id: 4,
    image:
      "https://res.cloudinary.com/ugwutotheeshoes/image/upload/v1648827303/Trailer/Action/MV5BOGE2NWUwMDItMjA4Yi00N2Y3LWJjMzEtMDJjZTMzZTdlZGE5XkEyXkFqcGdeQXVyODk4OTc3MTY_._V1__uzkz5r.jpg",
    name: "home alone without guns",
    genre: "action, comedy",
    ratings: "/10",
    url: "/1",
    text: "view details",
  },
];

export const movies = [
  {
    id: 1,
    name: "Creed III",
    category: "action",
    genre: "Sports, Drama",
    ratings: 7.3,
    video: "https://youtube.com/watch?v=AHmCH7iB_IM",
    img: "",
    poster: "",
    details:
      "Still dominating the boxing world, Adonis Creed is thriving in his career and family life. When Damian, a childhood friend and former boxing prodigy resurfaces after serving time in prison, he's eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian -- a fighter who has nothing to lose.",
    director: "Michael B. Jordan",
    writers: "Ryan Coogler, Keenan Coogler, Zach Baylin, Sylvester Stallone",
    casts:
      "Michael B. Jordan, Tessa Thompson, Jonathan Majors, Wood Harris, Mila Davis-Kent, Florian Munteanu, Phylicia Rashad",
    release: "3 March 2023",
  },
  {
    id: 2,
    name: "John Wick: Chapter 4",
    front: true,
    border: "right",
    category: "action",
    genre: "Action, Crime, Thriller",
    ratings: 8.5,
    video: "https://www.youtube.com/watch?v=qEVUtrk8_B4",
    img: "",
    poster: "",
    details:
      "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    director: "Chad Stahelski",
    writers: "Shay Hatten, Michael Finch, Derek Kolstad",
    casts:
      "Keanu Reeves, Donnie Yen, Bill Skarsgård, Laurence Fishburne, Hiroyuki Sanada, Shamier Anderson, Lance Reddick, Rina Sawayama, Scott Adkins, Ian McShane",
    release: "24 March, 2023",
  },
  {
    id: 3,
    name: "Ant-Man and the Wasp: Quantumania",
    category: "action",
    genre: "Action, Adventure, Comedy",
    ratings: 6.4,
    video: "https://www.youtube.com/watch?v=ZlNFpri-Y40",
    img: "",
    poster: "",
    details:
      "Scott Lang and Hope Van Dyne, along with Hank Pym and Janet Van Dyne, explore the Quantum Realm, where they interact with strange creatures and embark on an adventure that goes beyond the limits of what they thought was possible.",
    director: "Peyton Reed",
    writers: "Jeff Loveness, Stan Lee, Larry Lieber Jack Kirby",
    casts:
      "Paul Rudd, Evangeline Lilly, Jonathan Majors, Kathryn Newton, David Dastmalchian, Katy O'Brian, William Jackson Harper, Bill Murray, Michelle Pfeiffer, Corey Stoll, Michael Douglas",
    release: "February 17, 2023",
  },
  {
    id: 4,
    name: "Creed III",
    category: "action",
    genre: "Action, Adventure, Thriller",
    ratings: "none",
    video: "https://www.youtube.com/watch?v=2m1drlOZSDw",
    img: "",
    poster: "",
    details:
      "Mission: Impossible – Dead Reckoning Part One is an upcoming American action spy film written, produced, and directed by Christopher McQuarrie. It is the sequel to Mission: Impossible – Fallout and is the seventh and penultimate installment in the Mission: Impossible film series.",
    director: "Christopher McQuarrie",
    writers: "Bruce Geller, Christopher McQuarrie",
    casts:
      "Tom Cruise, Ving Rhames, Simon Pegg, Rebecca Ferguson, Vanessa Kirby, Hayley Atwell, Shea Whigham, Pom Klementieff, Esai Morales, Rob Delaney, Henry Czerny, Cary Elwes",
    release: "14 July, 2023",
  },
  {
    id: 5,
    name: "Dungeons & Dragons: Honor Among Thieves",
    category: "adventure",
    genre: "Adventure, Action, Fantasy",
    ratings: 8,
    video: "https://www.youtube.com/watch?v=IiMinixSXII",
    img: "",
    poster: "",
    details:
      "A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a long lost relic, but their charming adventure goes dangerously awry when they run afoul of the wrong people.",
    director: "John Francis Daley, Jonathan Goldstein",
    writers:
      "Jonathan Goldstein, John Francis Daley, Michael Gilio, Chris McKay",
    casts:
      "Chris Pine, Michelle Rodriguez, Regé-Jean Page, Justice Smith, Sophia Lillis, Hugh Grant",
    release: "7 April, 2023",
  },
  {
    id: 5,
    name: "Dungeons & Dragons: Honor Among Thieves",
    category: "adventure",
    genre: "Adventure, Action, Fantasy",
    ratings: 8,
    video: "https://www.youtube.com/watch?v=IiMinixSXII",
    img: "",
    poster: "",
    details:
      "A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a long lost relic, but their charming adventure goes dangerously awry when they run afoul of the wrong people.",
    director: "John Francis Daley, Jonathan Goldstein",
    writers:
      "Jonathan Goldstein, John Francis Daley, Michael Gilio, Chris McKay",
    casts:
      "Chris Pine, Michelle Rodriguez, Regé-Jean Page, Justice Smith, Sophia Lillis, Hugh Grant",
    release: "7 April, 2023",
  },
  {
    id: 5,
    name: "Dungeons & Dragons: Honor Among Thieves",
    category: "adventure",
    genre: "Adventure, Action, Fantasy",
    ratings: 8,
    video: "https://www.youtube.com/watch?v=IiMinixSXII",
    img: "",
    poster: "",
    details:
      "A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a long lost relic, but their charming adventure goes dangerously awry when they run afoul of the wrong people.",
    director: "John Francis Daley, Jonathan Goldstein",
    writers:
      "Jonathan Goldstein, John Francis Daley, Michael Gilio, Chris McKay",
    casts:
      "Chris Pine, Michelle Rodriguez, Regé-Jean Page, Justice Smith, Sophia Lillis, Hugh Grant",
    release: "7 April, 2023",
  },
  {
    id: 6,
    name: "Indiana Jones and the Dial of Destiny",
    category: "adventure",
    genre: "Adventure, Action, ",
    ratings: "none",
    video: "https://www.youtube.com/watch?v=ZfVYgWYaHmE",
    img: "",
    poster: "",
    details: "none",
    director: "James Mangold",
    writers:
      "Jez Butterworth, John-Henry Butterworth, David Koepp, James Mangold, George Lucas, Philip Kaufman",
    casts:
      "Harrison Ford, Phoebe Waller-Bridge, Antonio Banderas, John Rhys-Davies, Shaunette Renée Wilson, Thomas Kretschmann, Toby Jones, Boyd Holbrook, Olivier Richters, Ethann Isidore, Mads Mikkelsen",
    release: "30 June, 2023",
  },
  {
    id: 7,
    name: "Guardians of the Galaxy Vol. 3",
    front: true,
    border: "left",
    category: "adventure",
    genre: "Adventure, Action, Comedy",
    ratings: "none",
    video: "https://www.youtube.com/watch?v=JqcncLPi9zw",
    img: "",
    poster: "",
    details:
      "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.",
    director: "James Gunn",
    writers: "James Gunn, Dan Abnett, Andy Lanning",
    casts:
      "Chris Pratt, Zoe Saldaña, Dave Bautista, Karen Gillan, Pom Klementieff, Vin Diesel, Bradley Cooper, Sean Gunn, Chukwudi Iwuji, Will Poulter, Elizabeth Debicki, Maria Bakalova, Sylvester Stallone",
    release: "May 5, 2023",
  },
  {
    id: 8,
    name: "Peter Pan & Wendy",
    category: "adventure",
    genre: "Adventure, Action, Fantasy",
    ratings: "none",
    video: "https://www.youtube.com/watch?v=9Ji5U2sTlLU",
    img: "",
    poster: "",
    details:
      "Wendy Darling, a young girl looking to avoid boarding school, meets Peter Pan, a boy who refuses to grow up. Wendy, her brothers, and Tinker Bell travel with Peter to the magical world of Neverland, where she encounters an evil pirate captain.",
    director: "David Lowery",
    writers: "David Lowery, Toby Halbrooks",
    casts:
      "Jude Law, Alexander Molony, Ever Anderson, Yara Shahidi, Alyssa Wapanatâhk, Joshua Pickering, Jacobi Jupe, Molly Parker, Alan Tudyk, Jim Gaffigan",
    release: "28 April, 2023",
  },
  {
    id: 9,
    name: "Spider-Man: Across the Spider-Verse",
    front: true,
    border: "right",
    category: "animation",
    genre: "Animation, Action, Adventure, Comedy",
    ratings: 8,
    video: "https://www.youtube.com/watch?v=cqGjhVJWtEg",
    img: "",
    poster: "",
    details:
      "After reuniting with Gwen Stacy, Brooklyn's full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. However, when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders. He must soon redefine what it means to be a hero so he can save the people he loves most.",
    director: "Joaquim Dos Santos, Justin K. Thompson, Kemp Powers",
    writers: "Phil Lord, Christopher Miller, David Callaham",
    casts:
      "Shameik Moore, Hailee Steinfeld, Jake Johnson, Issa Rae, Daniel Kaluuya, Jason Schwartzman, Brian Tyree Henry, Luna Lauren Vélez, Greta Lee, Rachel Dratch, Jorma Taccone, Shea Whigham, Oscar Isaac",
    release: " 2 June, 2023",
  },
  {
    id: 10,
    name: "The Super Mario Bros. Movie",
    category: "animation",
    genre: "Animation, Adventure, Comedy",
    ratings: "none",
    video: "https://www.youtube.com/watch?v=TnGl01FkMMo",
    img: "",
    poster: "",
    details:
      "With help from Princess Peach, Mario gets ready to square off against the all-powerful Bowser to stop his plans from conquering the world.",
    director: "Aaron Horvath, Michael Jelenic",
    writers: "Matthew Fogel",
    casts:
      "Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black, Keegan-Michael Key, Seth Rogen, Fred Armisen, Sebastian Maniscalco, Charles Martinet, Kevin Michael Richardson",
    release: "31 March, 2023",
  },
  {
    id: 11,
    name: "",
    front: true,
    border: "left",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 12,
    name: "",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 13,
    name: "",
    front: true,
    border: "right",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 14,
    name: "",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 15,
    name: "",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 16,
    name: "",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 17,
    name: "",
    front: true,
    border: "left",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 18,
    name: "",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 19,
    name: "",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 20,
    name: "",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
  {
    id: 21,
    name: "",
    category: "",
    genre: "",
    ratings: 8,
    video: "",
    img: "",
    poster: "",
    details: "",
    director: "",
    writers: "",
    casts: "",
    release: "",
  },
];
